/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pes.Front;
import com.pes.Classes.Operacoes;
/**
 *
 * @author User
 */
public class CalculaDORa extends javax.swing.JFrame {
    
//                               SE LIGA!
    
    
    
//para encontrar as anotações, press ctrl+f e digite "atencao", só lembre de deletar a anotação depois.
//qualquer coisa que você precise anotar pra fazer depois, faça uma anotação com "atencao" pra ficar fácil de achar depois. 
    


//                               SE LIGA!
   int contadorOperacoes = 0;
   Operacoes Resultados = new Operacoes();
   boolean operacoesAnteriores=false;
   String saida = "";
   String entrada = "";
   String calculo = "";
   String resultadoAnterior = "";
    /*
     *
     * Creates new form CalculaDORa
     */

    public CalculaDORa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSaida = new javax.swing.JTextField();
        jButtonPersent = new javax.swing.JButton();
        jButtonRoot = new javax.swing.JButton();
        jButtonPower = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonMultiple = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonLess = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonErase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CalculaDORa");
        setBackground(new java.awt.Color(255, 153, 255));

        jTextFieldSaida.setEditable(false);
        jTextFieldSaida.setBackground(new java.awt.Color(109, 122, 97));
        jTextFieldSaida.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jTextFieldSaida.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldSaida.setAutoscrolls(false);

        jButtonPersent.setBackground(new java.awt.Color(255, 204, 204));
        jButtonPersent.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jButtonPersent.setText("%");
        jButtonPersent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersentActionPerformed(evt);
            }
        });

        jButtonRoot.setBackground(new java.awt.Color(255, 204, 204));
        jButtonRoot.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jButtonRoot.setText("R");
        jButtonRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRootActionPerformed(evt);
            }
        });

        jButtonPower.setBackground(new java.awt.Color(255, 204, 204));
        jButtonPower.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        jButtonPower.setText("^");
        jButtonPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPowerActionPerformed(evt);
            }
        });

        jButtonDivide.setBackground(new java.awt.Color(255, 204, 204));
        jButtonDivide.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButtonDivide.setText("/");
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });

        jButtonMultiple.setBackground(new java.awt.Color(255, 204, 204));
        jButtonMultiple.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButtonMultiple.setText("*");
        jButtonMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultipleActionPerformed(evt);
            }
        });

        jButtonPlus.setBackground(new java.awt.Color(255, 204, 204));
        jButtonPlus.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonLess.setBackground(new java.awt.Color(255, 204, 204));
        jButtonLess.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButtonLess.setText("-");
        jButtonLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLessActionPerformed(evt);
            }
        });

        jButtonEqual.setBackground(new java.awt.Color(255, 204, 204));
        jButtonEqual.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButtonEqual.setText("=");
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 204, 204));
        jButton7.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 204, 204));
        jButton8.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 204, 204));
        jButton9.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 204, 204));
        jButton5.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 204));
        jButton6.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton0.setBackground(new java.awt.Color(255, 204, 204));
        jButton0.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonDot.setBackground(new java.awt.Color(255, 204, 204));
        jButtonDot.setFont(new java.awt.Font("Aharoni", 0, 48)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });

        jButtonErase.setBackground(new java.awt.Color(255, 204, 204));
        jButtonErase.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jButtonErase.setText("AC");
        jButtonErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEraseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSaida)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPersent, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonErase, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonLess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonMultiple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonPersent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonErase, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLess, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPersentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersentActionPerformed
        // TODO add your handling code here:
        entrada = jTextFieldSaida.getText();
        Resultados.setValorUm(Double.parseDouble(entrada));
        saida = "" + Resultados.calcularPorcentagem();
        jTextFieldSaida.setText(saida);
        resultadoAnterior = saida;
        operacoesAnteriores = true;
        entrada = saida;
        contadorOperacoes = contadorOperacoes + 1;
        calculo = "CANSEI DESSA PORRA";
        
    }//GEN-LAST:event_jButtonPersentActionPerformed

    private void jButtonRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRootActionPerformed
        // TODO add your handling code here:
        entrada = jTextFieldSaida.getText();
        Resultados.setValorUm(Double.parseDouble(entrada));
        saida = "" + Resultados.calcularRaizQuadrada();
        jTextFieldSaida.setText(saida);
        resultadoAnterior = saida;
        operacoesAnteriores = true;
        entrada = saida;
        contadorOperacoes = contadorOperacoes + 1;
        calculo = "raiz";
        
    }//GEN-LAST:event_jButtonRootActionPerformed

    private void jButtonPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPowerActionPerformed
        // TODO add your handling code here:
        if (Resultados.getValorDois()<=0) Resultados.setValorDois(1);
        if (!calculo.equals("") && !calculo.equals("potencia")){
            if (igualdadeSoma())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeSubtracao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeMultiplicacao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeDivisao())saida = "" + Resultados.getValorAuxiliar();
            jTextFieldSaida.setText(saida);
            calculo = "potencia";
            verificarOperacoes();
            resultadoAnterior = saida;
            return;
        }
        calculo = "potencia";
        verificarOperacoes();
        if (contadorOperacoes >= 2){
        saida = "" + Resultados.calcularPotencia();
        jTextFieldSaida.setText(saida);
        resultadoAnterior = saida;
        }
        
    }//GEN-LAST:event_jButtonPowerActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        // TODO add your handling code here:
        if (contadorOperacoes == 0) Resultados.setValorDois(1);
        if (!calculo.equals("") && !calculo.equals("divisao")){
            if (igualdadeSoma())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeSubtracao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeMultiplicacao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadePotencia()) saida = "" + Resultados.getValorAuxiliar();
            jTextFieldSaida.setText(saida);
            calculo = "divisao";
            verificarOperacoes();
            resultadoAnterior = saida;
            return;
        }
        calculo = "divisao";
        verificarOperacoes();
        if (contadorOperacoes > 1){
        saida = "" + Resultados.calcularDivisao();
        jTextFieldSaida.setText(saida);
        resultadoAnterior = saida;
        }
        
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultipleActionPerformed
        // TODO add your handling code here:
        if (contadorOperacoes == 0)Resultados.setValorDois(1.0);
        if (!calculo.equals("") && !calculo.equals("multiplicacao")){
            if (igualdadeSoma())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeSubtracao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeDivisao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadePotencia()) saida = "" + Resultados.getValorAuxiliar();
            jTextFieldSaida.setText(saida);
            calculo = "multiplicacao";
            verificarOperacoes();
            resultadoAnterior = saida;
            return;
        }
        calculo = "multiplicacao";
        verificarOperacoes();
        if (contadorOperacoes >= 2){
        saida = "" + Resultados.calcularMultiplicacao();
        jTextFieldSaida.setText(saida);
        resultadoAnterior = saida;
        }
        
    }//GEN-LAST:event_jButtonMultipleActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        if (!calculo.equals("") && !calculo.equals("soma")){
            if (igualdadeDivisao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeSubtracao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeMultiplicacao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadePotencia()) saida = "" + Resultados.getValorAuxiliar();
            jTextFieldSaida.setText(saida);
            calculo = "soma";
            verificarOperacoes();
            resultadoAnterior = saida;
            return;
        }
        calculo = "soma";
        verificarOperacoes();
        if (contadorOperacoes >= 2){
        saida = "" + Resultados.calcularSoma();
        jTextFieldSaida.setText(saida);
        resultadoAnterior = saida;
        }
        
        
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLessActionPerformed
        // TODO add your handling code here:
        if (!calculo.equals("") && !calculo.equals("subtracao")){
            if (igualdadeSoma())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeDivisao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadeMultiplicacao())saida = "" + Resultados.getValorAuxiliar();
            if (igualdadePotencia()) saida = "" + Resultados.getValorAuxiliar();
            jTextFieldSaida.setText(saida);
            calculo = "subtracao";
            verificarOperacoes();
            resultadoAnterior = saida;
            return;
        }
        calculo = "subtracao";
        verificarOperacoes();
        if (contadorOperacoes >= 2){
        saida = "" + Resultados.calcularSubtracao();
        jTextFieldSaida.setText(saida);
        entrada = saida;
        resultadoAnterior = saida;
        }
        
    }//GEN-LAST:event_jButtonLessActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        // TODO add your handling code here:
        entrada = jTextFieldSaida.getText();
        verificarOperacoes();
        if (igualdadeSoma())saida = "" + Resultados.getValorAuxiliar();
        if (igualdadeSubtracao())saida = "" + Resultados.getValorAuxiliar();
        if (igualdadeMultiplicacao())saida = "" + Resultados.getValorAuxiliar();
        if (igualdadeDivisao())saida = "" + Resultados.getValorAuxiliar();
        if (igualdadePotencia())saida = "" + Resultados.getValorAuxiliar();
        jTextFieldSaida.setText(saida);
        resultadoAnterior = saida;
        contadorOperacoes = 1;
        
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().startsWith("0") && jTextFieldSaida.getText().endsWith("0")) saida = "";
        limpar();
        saida += "7";
         jTextFieldSaida.setText(saida);
        entrada += "7";
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().startsWith("0") && jTextFieldSaida.getText().endsWith("0")) saida = "";
        limpar();
        saida += "8";
         jTextFieldSaida.setText(saida);
        entrada += "8";
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().startsWith("0") && jTextFieldSaida.getText().endsWith("0")) saida = "";
        limpar();
        saida += "9";
         jTextFieldSaida.setText(saida);
        entrada += "9";

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().startsWith("0") && jTextFieldSaida.getText().endsWith("0")) saida = "";
        limpar();
        saida += "4";
         jTextFieldSaida.setText(saida);
        entrada += "4";

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().startsWith("0") && jTextFieldSaida.getText().endsWith("0")) saida = "";
        limpar();
        saida += "5";
         jTextFieldSaida.setText(saida);
        entrada += "5";
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().startsWith("0") && jTextFieldSaida.getText().endsWith("0")) saida = "";
        limpar();
        saida += "6";
         jTextFieldSaida.setText(saida);
        entrada += "6";
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().startsWith("0") && jTextFieldSaida.getText().endsWith("0")) saida = "";
        limpar();
        saida += "1";
         jTextFieldSaida.setText(saida);
        entrada += "1";
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().startsWith("0") && jTextFieldSaida.getText().endsWith("0")) saida = "";
        limpar();
        saida += "2";
         jTextFieldSaida.setText(saida);
        entrada += "2";

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().startsWith("0") && jTextFieldSaida.getText().endsWith("0")) saida = "";
        limpar();
        saida += "3";
         jTextFieldSaida.setText(saida);
        entrada += "3";

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        String auxiliarZero = jTextFieldSaida.getText();
        limpar();
        if (auxiliarZero.equals("")||
                auxiliarZero.equals("0")){
            saida = "0";
            jTextFieldSaida.setText(saida);
        }
        if (auxiliarZero.startsWith("1")||
                auxiliarZero.startsWith("2")||
                auxiliarZero.startsWith("3")||
                auxiliarZero.startsWith("4")||
                auxiliarZero.startsWith("5")||
                auxiliarZero.startsWith("6")||
                auxiliarZero.startsWith("7")||
                auxiliarZero.startsWith("8")||
                auxiliarZero.startsWith("9")) {
            saida += "0";
            entrada += "0";
            jTextFieldSaida.setText(saida);
        }
        
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().equals("")||jTextFieldSaida.getText().equals("0")){
            entrada = "0.";
            if (jTextFieldSaida.getText().equals("")) saida = "0.";
            if (jTextFieldSaida.getText().equals("0")) saida += "."; 
        } else{
            entrada += ".";
            saida += ".";
        }
        jTextFieldSaida.setText(saida);
        
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButtonEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEraseActionPerformed
        // TODO add your handling code here:
        Resultados.setValorAuxiliar(0);
        Resultados.setValorDois(0);
        Resultados.setValorUm(0);
        contadorOperacoes = 0;
        operacoesAnteriores = false;
        resultadoAnterior = "";
        saida = "";
        entrada = "";
        jTextFieldSaida.setText("");
        
    }//GEN-LAST:event_jButtonEraseActionPerformed

    public void verificarOperacoes (){
        
        if (contadorOperacoes == 0){
            Resultados.setValorUm(Double.parseDouble(entrada));
            contadorOperacoes = contadorOperacoes + 1;
            operacoesAnteriores = true;
            return;
        }
        if (contadorOperacoes >= 1) {
            if (contadorOperacoes > 1 && !resultadoAnterior.equals("")){
                Resultados.setValorUm(Double.parseDouble(resultadoAnterior));
            }
            Resultados.setValorDois(Double.parseDouble(entrada));
            contadorOperacoes = contadorOperacoes + 1;
            operacoesAnteriores = true;
            
        }
    }
   
    public void limpar(){
        if (operacoesAnteriores) {
            operacoesAnteriores = false;
            saida = "";
            entrada = "";
            jTextFieldSaida.setText(saida);
        }
    }
    public boolean igualdadePotencia (){
        boolean VF = false;
        if (calculo.equals("potencia")){
            Resultados.setValorDois(Double.parseDouble(entrada));
            if (!resultadoAnterior.equals("") && !resultadoAnterior.equals("0")){
                Resultados.setValorUm(Double.parseDouble(resultadoAnterior));
            }
            Resultados.calcularPotencia();
            VF = true;
        } 
        return VF;
        
    }
    public boolean igualdadeDivisao (){
        boolean VF = false;
        if (calculo.equals("divisao")){
            Resultados.setValorDois(Double.parseDouble(entrada));
            if (!resultadoAnterior.equals("") && !resultadoAnterior.equals("0")){
                Resultados.setValorUm(Double.parseDouble(resultadoAnterior));
            }
            Resultados.calcularDivisao();
            VF = true;
        }
        return VF;
        
    }
    public boolean igualdadeMultiplicacao (){
        boolean VF = false;
        if (calculo.equals("multiplicacao")){
            Resultados.setValorDois(Double.parseDouble(entrada));
            if (!resultadoAnterior.equals("") && !resultadoAnterior.equals("0")){
                Resultados.setValorUm(Double.parseDouble(resultadoAnterior));
            }
            Resultados.calcularMultiplicacao();
            VF = true;
        }
        return VF;
    }
    public boolean igualdadeSoma (){
        boolean VF = false;
        if (calculo.equals("soma")) {
            Resultados.setValorDois(Double.parseDouble(entrada));
            if (!resultadoAnterior.equals("") && !resultadoAnterior.equals("0")){
                Resultados.setValorUm(Double.parseDouble(resultadoAnterior));
            }
            Resultados.calcularSoma();
            VF = true;
        }
        return VF;
        
    }
    public boolean igualdadeSubtracao (){
        boolean VF = false;
        if (calculo.equals("subtracao")){
            Resultados.setValorDois(Double.parseDouble(entrada));
            if (!resultadoAnterior.equals("") && !resultadoAnterior.equals("0")){
                Resultados.setValorUm(Double.parseDouble(resultadoAnterior));
            }
            Resultados.calcularSubtracao();
            VF = true;
        }
        return VF;
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculaDORa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculaDORa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculaDORa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculaDORa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculaDORa().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonErase;
    private javax.swing.JButton jButtonLess;
    private javax.swing.JButton jButtonMultiple;
    private javax.swing.JButton jButtonPersent;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPower;
    private javax.swing.JButton jButtonRoot;
    private javax.swing.JTextField jTextFieldSaida;
    // End of variables declaration//GEN-END:variables
}
